import { useState, useEffect, useRef } from 'react';
import { X, Terminal } from 'lucide-react';
import axios from 'axios';

interface LogModalProps {
  isOpen: boolean;
  onClose: () => void;
  jobId: number | null;
}

export default function LogModal({ isOpen, onClose, jobId }: LogModalProps) {
  const [logs, setLogs] = useState<string>("Waiting for logs...");
  const logEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    let interval: NodeJS.Timeout;
    
    if (isOpen && jobId !== null) {
      // Fetch immediately
      fetchLogs();
      // Then poll every 1s
      interval = setInterval(fetchLogs, 1000);
    }

    return () => {
      if (interval) clearInterval(interval);
    };
  }, [isOpen, jobId]);

  const fetchLogs = async () => {
    if (jobId === null) return;
    try {
      const res = await axios.get(`http://localhost:8888/api/jobs/${jobId}/logs`);
      
      // Clean up carriage returns (\r) often generated by tqdm so they don't look weird
      let rawText = res.data.logs || "Waiting for logs...";
      
      // We can split by \n and for each line, if there's a \r, take the last part of it
      const lines = rawText.split('\n').map((line: string) => {
        const parts = line.split('\r');
        return parts[parts.length - 1]; // Only take what comes after the last \r
      });
      
      setLogs(lines.join('\n'));
    } catch (e) {
      console.error("Failed to fetch logs", e);
    }
  };

  useEffect(() => {
    // Auto-scroll to bottom when logs update
    logEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [logs, isOpen]);

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black/80 backdrop-blur-sm flex items-center justify-center z-50 p-4 lg:p-12">
      <div className="bg-neutral-900 border border-neutral-800 rounded-2xl w-full max-w-5xl h-[80vh] flex flex-col shadow-2xl overflow-hidden animate-in fade-in zoom-in-95 duration-200">
        
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-neutral-800 bg-neutral-950/50">
          <div className="flex items-center space-x-3 text-neutral-200">
            <Terminal size={20} className="text-purple-400" />
            <h2 className="text-lg font-medium">Task Logs (Job #{jobId})</h2>
          </div>
          <button 
            onClick={onClose}
            className="p-2 hover:bg-neutral-800 rounded-lg text-neutral-400 hover:text-white transition-colors"
          >
            <X size={20} />
          </button>
        </div>

        {/* Console Area */}
        <div className="flex-1 overflow-auto bg-black p-6 font-mono text-sm leading-relaxed text-neutral-300">
          <pre className="whitespace-pre-wrap break-words">{logs}</pre>
          <div ref={logEndRef} />
        </div>
      </div>
    </div>
  );
}
